version: "3"

services:
  server:
    build: ./reversed-app-server
    ports:
      - "8000:8000"
  client:
    build: ./reversed-app-client
    ports:
      - "3000:3000"
    depends_on:
      - server
